"use client";

import { DocsContent, DocsPagination, DocsCallout } from "@/components/docs";
import { useDocsTheme } from "@/app/docs/layout";

export default function FAQPage() {
  const { isDark } = useDocsTheme();

  const textPrimary = isDark ? '#ffffff' : '#0a0a0a';
  const textMuted = isDark ? '#9ca3af' : '#6b7280';
  const bgSubtle = isDark ? 'rgba(255, 255, 255, 0.02)' : 'rgba(0, 0, 0, 0.02)';
  const borderColor = isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)';

  const faqs = [
    {
      question: "What frameworks does Exact support?",
      answer: "Exact supports React, Vue 3, Svelte, Next.js, Nuxt, SvelteKit, Astro, and more. It automatically detects your framework and adapts its suggestions accordingly."
    },
    {
      question: "Is my code sent to the cloud?",
      answer: "Yes, code snippets are sent to our AI servers for processing. All data is encrypted in transit and at rest, and we never store your code longer than necessary to process requests. Enterprise customers can opt for on-premise deployment."
    },
    {
      question: "Can I use Exact offline?",
      answer: "Basic editing features work offline, but AI-powered features require an internet connection. We're working on local model support for future releases."
    },
    {
      question: "Does Exact work with my existing VS Code extensions?",
      answer: "The Exact VS Code extension is designed to complement your existing setup. Most extensions work normally alongside Exact. If you encounter conflicts, check our compatibility guide."
    },
    {
      question: "How does Exact learn my coding style?",
      answer: "Exact analyzes your existing codebase to understand your patterns, naming conventions, and preferences. The more you use it, the more personalized suggestions become."
    },
    {
      question: "Is there a free tier?",
      answer: "Yes! The free tier includes 100 AI requests per month, basic code generation, and component polish features. Upgrade to Pro for unlimited requests and advanced features."
    },
    {
      question: "Can I use Exact for commercial projects?",
      answer: "Absolutely. Both free and paid tiers can be used for commercial projects. You own all code generated by Exact."
    },
    {
      question: "How accurate is the AI code generation?",
      answer: "Exact achieves over 90% accuracy on common UI patterns. Complex logic may require some adjustments. Always review generated code before using it in production."
    },
    {
      question: "Does Exact support custom design systems?",
      answer: "Yes! You can configure Exact to understand your design tokens, component library, and styling conventions. This ensures generated code matches your existing patterns."
    },
    {
      question: "How do I report bugs or request features?",
      answer: "Use the feedback button in the app (? icon in bottom right) or email support@exact.dev. We actively incorporate user feedback into our roadmap."
    },
  ];

  return (
    <DocsContent
      title="Frequently Asked Questions"
      description="Answers to common questions about Exact."
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        {faqs.map((faq, index) => (
          <div
            key={index}
            style={{
              backgroundColor: bgSubtle,
              border: `1px solid ${borderColor}`,
              borderRadius: '12px',
              padding: '20px',
            }}
          >
            <h3 style={{ color: textPrimary, fontSize: '16px', fontWeight: 600, marginBottom: '12px' }}>
              {faq.question}
            </h3>
            <p style={{ color: textMuted, lineHeight: '1.7', margin: 0 }}>
              {faq.answer}
            </p>
          </div>
        ))}
      </div>

      <DocsCallout type="info" title="Still have questions?">
        <p>Can&apos;t find what you&apos;re looking for? Reach out to our support team at{" "}
          <a href="mailto:support@exact.dev" style={{ color: '#60a5fa', textDecoration: 'underline' }}>
            support@exact.dev
          </a>{" "}
          or join our{" "}
          <a href="/community" style={{ color: '#60a5fa', textDecoration: 'underline' }}>
            Discord community
          </a>.
        </p>
      </DocsCallout>

      <DocsPagination
        prev={{ title: "Billing", href: "/docs/billing" }}
        next={{ title: "Changelog", href: "/docs/changelog" }}
      />
    </DocsContent>
  );
}
